version: '3.9'
services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: secret_password
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    environment:
      DB_URI: postgresql://postgres:secret_password@db:5432/bingo
      DISCORD_TOKEN:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  overlay:
    build: overlay/.
    ports:
      - "8080:8080"
    depends_on:
      - bot
